### ISSUE TITLE
Not deploying to same branch

### ISSUE THREAD

**Issue by kay-is** [enriikke/gatsby-gh-pages-action#11]
There is a line of code that prevents deployment on the same branch, probably to get rid of recursion.

When I trigger with Cron, this should be okay, because pushes on that branch are ignored by the action.

**Comment by enriikke** [comment]
Hi @kay-is! Thanks for opening up the issue. You are correct about that line being there to prevent this action to be triggered by its own push.

I'm not sure if I follow your particular use case but I'll be happy to look at this (or potentially other options) if you can provide more context.

**Comment by kay-is** [comment]
I wanted to deploy once a day with cron, which didn't work.

**Comment by enriikke** [comment]
This was addressed in https://github.com/enriikke/gatsby-gh-pages-action/pull/41 😃
