### ISSUE TITLE
Not deploying to same branch in other deploy-repo

### ISSUE THREAD

**Issue by rolandharrison** [enriikke/gatsby-gh-pages-action#19]
Similar to [#11](https://github.com/enriikke/gatsby-gh-pages-action/issues/11) except the specific use case is when the deploy repository is not the same as the repository that is running the action.

**Comment by richardrobberse** [comment]
Facing the same issue now...
@enriikke please merge the fix because this is probably confusing a lot of people!

**Comment by enriikke** [comment]
This was addressed in https://github.com/enriikke/gatsby-gh-pages-action/pull/41 😃
