### ISSUE TITLE
Copying README.md to deploy branch

### ISSUE THREAD

**Issue by BTx123** [enriikke/gatsby-gh-pages-action#22]
I was wondering if there is a way to get the `README.md` copied to the deployed branch, similar to how `CNAME` is copied. Not sure if this should be part of the action or a step taken before executing the action.

**Comment by py563** [comment]
hi @BTx123 any reason to copy Readme file to deployed branch. I guess copying readme shouldn't be part of any action. 

But you can try to manually force it to be done i guess by having a copy in static folder. I haven't explored much in Gatsby but the above do the job in Hugo, per my knowledge I feel both Gatsby and Hugo follow similar process for files in static folder when building.

**Comment by BTx123** [comment]
ok thanks! I'll try that out.
