### ISSUE TITLE
Action is failing to build with npm when no gatsby-args are provided

### ISSUE THREAD

**Issue by piraces** [enriikke/gatsby-gh-pages-action#25]
Hello,

First of all, thanks for this awesome Github action!

I'm having problems when deploying my site using this action and I think its related with the `gatsby-args` option.

My `build` npm script is simply set to `gatsby build`. When the action runs, if no `gatsby-args` provided, the script executed is `gatsby build ""` which results in error since `""` is invalid for the command.

Please see a log example:
```shell
Ready to build your Gatsby site!
Building with: npm run build 
npm run build 

> piraces.dev@3.0.0 build /home/runner/work/piraces.dev/piraces.dev
> gatsby build ""

error gatsby build

Build a Gatsby project.

Options:
  --verbose                   Turn on verbose output  [boolean] [default: false]
  --no-color, --no-colors     Turn off the color in output  [boolean] [default: false]
  --json                      Turn on the JSON logger  [boolean] [default: false]
  --prefix-paths              Build site with link paths prefixed with the pathPrefix value in gatsby-config.js. Default is env.PREFIX_PATHS or false.  [boolean] [default: false]
  --no-uglify                 Build site without uglifying JS bundles (for debugging).  [boolean] [default: false]
  --profile                   Build site with react profiling (this can add some additional overhead). See https://reactjs.org/docs/profiler  [boolean] [default: false]
  --open-tracing-config-file  Tracer configuration file (OpenTracing compatible). See https://gatsby.dev/tracing  [string]
  -h, --help                  Show help  [boolean]
  -v, --version               Show the version of the Gatsby CLI and the Gatsby package in the current project  [boolean]
⠀
Unknown argument: 
``` 

I think this lines are the ones that are invoking the command with the empty args:

https://github.com/enriikke/gatsby-gh-pages-action/blob/7790d8577bc54376c614d3d2784154ec03a2f5e1/index.js#L31-L34

**Comment by scanning** [comment]
I hit the same problem with yarn.  It was running `yarn build ''`.  I worked around this by specifying a no-op `gatsby-args: --no-color`

**Comment by enriikke** [comment]
Thanks for reporting this @piraces! ✨ 

I just opened a PR that does some clean up and fixes this issue. Apologies for the trouble. 🙇
