### ISSUE TITLE
Skip-publish is listed as possible value, but action complains when using it

### ISSUE THREAD

**Issue by iranzo** [enriikke/gatsby-gh-pages-action#46]
![image](https://user-images.githubusercontent.com/312463/99395290-7ffcee80-28e0-11eb-8456-7be6d3b2eed1.png)

**Comment by iranzo** [comment]
Additionally when using `@main` instead of  version, it complaisn of non existing file:

![image](https://user-images.githubusercontent.com/312463/99395996-7de75f80-28e1-11eb-9c09-976b48c5c028.png)

**Comment by kenjdavidson** [comment]
`skip-publish` is only available in `enriikke/gatsby-gh-pages-action@v2`
You can't use the `main` branch as there is no `dist` folder published

**Comment by iranzo** [comment]
Thanks @kenjdavidson the issue is that v2.1.1 > v2 (there's another issue open for that) and github actions marketplace is the one showing v.2.1.1 as the latest one

**Comment by enriikke** [comment]
Tags should be fixed now. 🚀
