### ISSUE TITLE
Could you release a new tag?

### ISSUE THREAD

**Issue by kenjdavidson** [enriikke/gatsby-gh-pages-action#48]
Can use the @main branch as there is no `/dist` published.  Really want to use the new `working-dir` feature without forking.

**Comment by kenjdavidson** [comment]
Sorry about the edits, I'm an idiot and didn't see the `release` workflow.

**Comment by jumpalottahigh** [comment]
I'm after the same thing - using the `working-dir` flag, but it seemed like the action does not take it into account. I set up the action as it's shown in the example on the marketplace page. Then I noticed that the `v2` doesn't have the `working-dir` flag implemented yet, but it does live in main. Is there any way to point to that version of the action?

**Comment by budavariam** [comment]
I was able to solve this for myself with a fork, build and a retag, but it would be simpler, if there was a new tag in this repo that contains the `working-dir` feature

**Comment by antranapp** [comment]
Banging my head since 2 days why `working-dir` didn't work. Finally find this issue. @enriikke  could you please tag a new release?

There should be a way to point to `main` to be honest

**Comment by enriikke** [comment]
Tags should be fixed now. 🚀
