### ISSUE TITLE
Standardize on tags naming

### ISSUE THREAD

**Issue by iranzo** [enriikke/gatsby-gh-pages-action#50]
Some tags are named vX.Y.Z others like X.Y.Z, one naming schema should be used and remove the other tags.

If format decided is vX.Y.Z. the PR #49  should be updated to match the v*.*.* naming schema

**Comment by enriikke** [comment]
Thank you for your PR. We have a workflow to handle this going forward and consistently tag in the `v.X.Y.Z` format. I'll be keeping the other tags for backwards compatibility in case some folks are working based on them. The README does specify the `v` prefix though. 😃
