### ISSUE TITLE
Support for custom deploy user

### ISSUE THREAD

**Issue by lukasbach** [enriikke/gatsby-gh-pages-action#54]
Currently, the action hardcodes the authoring git user and email adress that authors the deploy commit. It'd be great if you could customize that when using the action. I'd be happy to take a PR on that if you want.

**Comment by enriikke** [comment]
Closed on https://github.com/enriikke/gatsby-gh-pages-action/pull/55

**Comment by lukasbach** [comment]
Hi @enriikke, I'd be happy if you could deploy a new version of the action, so that the added changes are available in workflows.

**Comment by enriikke** [comment]
Done @lukasbach! 😃

**Comment by lukasbach** [comment]
Great, thanks :)
